### ISSUE TITLE
Perfomance tests

### ISSUE THREAD

**Issue by pestanko** [vmuzikar/PA036-2017-project#2]
- pgFouine
- https://www.datadoghq.com/blog/100x-faster-postgres-performance-by-changing-1-line/
- http://www.revsys.com/writings/postgresql-performance.html
- https://wiki.postgresql.org/wiki/Pgbenchtesting
- http://www.hammerdb.com/
- http://longwhiteclouds.com/2014/11/27/performance-testing-mysql-and-postgresql-with-hammerdb-and-pgbench/
- https://wiki.postgresql.org/wiki/Monitoring
- https://wiki.postgresql.org/wiki/Performance_Analysis_Tools
- https://wiki.postgresql.org/wiki/Performance_Optimization
- https://github.com/darold/pgcluu
- http://opm.io/

**Comment by pestanko** [comment]
https://wiki.postgresql.org/wiki/Performance_Analysis_Tools

**Comment by pestanko** [comment]
pgFouine

**Comment by Pepo48** [comment]
https://wiki.postgresql.org/wiki/Pgbenchtesting
http://www.hammerdb.com/
http://longwhiteclouds.com/2014/11/27/performance-testing-mysql-and-postgresql-with-hammerdb-and-pgbench/
https://wiki.postgresql.org/wiki/Monitoring
https://wiki.postgresql.org/wiki/Performance_Analysis_Tools
https://wiki.postgresql.org/wiki/Performance_Optimization
https://github.com/darold/pgcluu
http://opm.io/

**Comment by Pepo48** [comment]
HammerDB documentation:
http://www.hammerdb.com/hammerdb_postgres_oltp.pdf
http://www.hammerdb.com/hammerdb_metrics.pdf
http://www.hammerdb.com/hammerdb_autopilot.pdf
