### ISSUE TITLE
Authorization Method: Policies

### ISSUE THREAD

**Issue by pestanko** [vmuzikar/PA036-2017-project#5]

**Comment by gevo20** [comment]
[https://blog.2ndquadrant.com/application-users-vs-row-level-security/](https://blog.2ndquadrant.com/application-users-vs-row-level-security/)
[https://blog.2ndquadrant.com/auditing-users-and-roles-in-postgresql/](https://blog.2ndquadrant.com/auditing-users-and-roles-in-postgresql/)

**Comment by gevo20** [comment]
CREATE USER cashier;
CREATE USER manager;
CREATE USER marketer;

GRANT cashier TO manager;

GRANT ALL ON customer TO cashier;
GRANT ALL ON customer TO manager;
GRANT ALL ON customer TO marketer;

GRANT ALL ON orders TO cashier;
GRANT ALL ON orders TO manager;
GRANT ALL ON orders TO marketer;

Čo sa týka policies, tak som ich nechal pre všetkých rovnaké. každý môže spraviť SELECT na riadok v ktorom má pre stĺpec 'records_select' svoje meno. Podobne pri UPDATE a DELETE (policies  mi to však obmedzujú a ide urobiť UPDATE/DELETE na riadok len ak má na ňom user právo SELECTu).

**Comment by vmuzikar** [comment]
👍🏻

Jj, i u VIEWS/TRIGGERS je tam stejné omezení - pokud nemá SELECT, nemá ani UPDATE/DELETE.

Máme už nějak řešené to random rozhození práv?

**Comment by vmuzikar** [comment]
Jo vlastně ale - ještě musíme zohlednit INSERT právo --> nebude všude ALL

**Comment by gevo20** [comment]
Random rozdelenie @pestanko  poriešil. Do súboru sa dajú zadať ako normálne reťazce a potom ich náhodne priraďuje do 3 stĺpcov.  
INSERT som dal zatiaľ každej roly na všetky tabuľky, nejako som ho extra neriešil.  Cez POLICY to asi nemá zmysel a GRANT som dal pekne ALL :D

**Comment by vmuzikar** [comment]
Když děláš UPDATE/DELETE a narazíš (mimo ostatní) i na řádek, kam nemáš práva, rušíš celou transakci? Nebo jen skipneš řádek? Ať to máme jednotný.

**Comment by gevo20** [comment]
Nie som si istý či dobre chápem. Ale.. ja keď pustím napríklad DELETE tak mi to vymaže všetky riadky kde má aktuálna rola právo na SELECT a DELETE.... na šupu a nič tam neriešim.
